config/routes.rb
Rails.application.routes.draw do
  resources :sightings
  resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/animal.rb
class Animal < ApplicationRecord
    has_many :sightings
    validates :name, :latin_name, :kingdom, presence: true
    validates :name, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
    belongs_to :animal
    validates :animal_id, :date, :time, :region, presence: true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    def index
        @animals = Animal.all
    end
    
    def new
        @animal = Animal.new
    end
    
    def create
        @animal = Animal.new(animal_params)
        if @animal.valid?
            @animal.save
            redirect_to animals_path
        else
            render action: :new       
        end
    end
    
    def show
        @animal = Animal.find(params[:id])
    end
    
    def edit
        @animal = Animal.find(params[:id])
    end
    
    def update
        @animal = Animal.find(params[:id])
        if @animal.update_attributes(animal_params)
            redirect_to animals_path
        else
            render action: :edit
        end
    end
    
    def destroy
        @animal = Animal.find(params[:id])
        @animal.destroy
        redirect_to animals_path
    end 
    
    private
    
    def animal_params
        params.require(:animal).permit(:name, :latin_name, :kingdom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
    
    def new
        animal = Animal.find(params[:animal_id])
        @animal = animal
        @sighting = animal.sightings.new
    end
    
    def create
        @sighting = Sighting.new(sighting_params)
        if @sighting.valid?
            @sighting.save
            redirect_to animal_path(@sighting.animal)
        else
            render action: :new       
        end
    end
       
    def edit
        @sighting = Sighting.find(params[:id])
    end
    
    def update
        @sighting = Sighting.find(params[:id])
        @sighting.update_attributes(sighting_params)
        redirect_to animal_path(@sighting.animal)
    end
    
    def destroy
        @sighting = Sighting.find(params[:id])
        @sighting.destroy
        redirect_to animal_path(@sighting.animal)
    end 
    
    private
    
    def sighting_params
        params.require(:sighting).permit(:animal_id, :date, :time, :latitude, :longitude, :region)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/edit.html.erb
<h4>Edit <%= @animal.name %></h4>
<p>All fields are required.</p>
<hr>

<%= render "layouts/animals_form" %>

<% if @animal.errors %>
    <ul>
        <% @animal.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<hr>
<a><%= link_to @animal.name + ": Delete", animal_path(@animal), :class => "btn btn-warning", method: :delete, data: {confirm: 'Are you totally totally sure?'}%></a>

app/views/animals/index.html.erb
<h1>Welcome to Forest Park Ranger Services</h1>
<hr>

<h4>Animal Database</h4>
<br />

<ol>
    <% @animals.each do |animal| %>
        <div>
            <a><%= link_to animal.name + ": Detailed Specs", animal_path(animal), :class => "btn btn-success" %></a>
        </div><br />
    <% end %>
</ol>
<br />
<h5>Click below to add a new animal to the database: </h5>
<a><%= link_to "Add New Animal", new_animal_path, :class => "btn btn-success" %></a>

app/views/animals/new.html.erb
<h4>Add New Animal</h4>
<p>Add a new animal to the database by completing this form. All fields required.</p>
<hr>

<%= render "layouts/animals_form" %>

<% if @animal.errors %>
    <ul>
        <% @animal.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/animals/show.html.erb
<h4><%= @animal.name %> Specs</h4>
<br />

<p>Animal Name: <%= @animal.name %></p>
<p>Animal Latin Name: <%= @animal.latin_name %></p>
<p>Kingdom: <%= @animal.kingdom %></p>
<a><%= link_to @animal.name + ": Edit", edit_animal_path(@animal), :class => "btn btn-success" %></a>
<hr>

<h4>Total <%= @animal.name %> Sightings: <%= @animal.sightings.count %></h4>
<a><%= link_to @animal.name + ': Add Sighting', new_sighting_path(animal_id: @animal.id), :class => "btn btn-success" %></a><br /><br />

<ul>
  <% @animal.sightings.each do |sighting| %>
    <p>Sighting Date: <%= sighting.date %></p>
    <p>Sighting Time: <%= sighting.time %></p>
    <p>Sighting Latitude & Longitude: <%= sighting.latitude %> - <%= sighting.longitude %></p> 
    <p>Sighting Region: <%= sighting.region %></p> 
    <div class><%= link_to 'Edit This Sighting', edit_sighting_path(sighting), :class => "btn btn-success" %></div>
    <hr>
  <% end %>
</ul>

app/views/layouts/_animals_form.html.erb
<%= form_for @animal do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br />
    
    <%= f.label :latin_name %>
    <%= f.text_field :latin_name %><br />
    
    <p>Kingdom (choose one):</p>
    &nbsp&nbsp&nbsp&nbsp&nbsp<%= f.radio_button :kingdom, 'Mammal', :checked =>true %>
    &nbsp&nbsp&nbsp&nbsp&nbsp<%= label :kingdom, 'Mammal' %></br>
    
    &nbsp&nbsp&nbsp&nbsp&nbsp<%= f.radio_button :kingdom, 'Bird' %>
    &nbsp&nbsp&nbsp&nbsp&nbsp<%= label :kingdom, 'Bird' %></br>
    
    &nbsp&nbsp&nbsp&nbsp&nbsp<%= f.radio_button :kingdom, 'Fish' %>
    &nbsp&nbsp&nbsp&nbsp&nbsp<%= label :kingdom, 'Fish' %></br>
    
    &nbsp&nbsp&nbsp&nbsp&nbsp<%= f.radio_button :kingdom, 'Reptile' %>
    &nbsp&nbsp&nbsp&nbsp&nbsp<%= label :kingdom, 'Reptile' %></br>
    
    &nbsp&nbsp&nbsp&nbsp&nbsp<%= f.radio_button :kingdom, 'Amphibian' %>
    &nbsp&nbsp&nbsp&nbsp&nbsp<%= label :kingdom, 'Amphibian' %></br></br>
    
    &nbsp&nbsp&nbsp&nbsp<%= f.submit 'Submit', :class => "btn btn-success"%>
<% end %><br />

app/views/layouts/_sightings_form.html.erb
<%= form_for @sighting do |f| %>
    <%= f.hidden_field :animal_id %>
    <%= f.label :date %>
    <%= f.text_field :date %><br />
    
    <%= f.label :time %>
    <%= f.text_field :time %><br />
    
    <%= f.label :latitude %>
    <%= f.text_field :latitude %><br />
    
    <%= f.label :longitude %>
    <%= f.text_field :longitude %><br />
    
    <%= f.label :region %>&nbsp&nbsp
    <%= f.select :region, (["North of 13", "South of 13"]) %><br /><br />
    
    &nbsp&nbsp&nbsp&nbsp<%= f.submit 'Submit', :class => "btn btn-success"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-image: <%= asset_path('Magical_forest2.jpeg') %>">
    <%= yield %>
  </body>
</html>

app/views/sightings/edit.html.erb
<h4>Edit Sighting:</h4>
<p>All fields are required.</p>
<hr>

<%= render "layouts/sightings_form" %>
<hr>

<% if @sighting.errors %>
    <ul>
        <% @sighting.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<a><%= link_to "Delete Sighting", sighting_path(@sighting), :class => "btn btn-warning", method: :delete, data: {confirm: 'Are you totally totally sure?'}%></a>

app/views/sightings/new.html.erb
<h4>Report New <%= @animal.name %> Sighting</h4>
<p>Add a new sighting to the database by completing this form. All fields required.</p>
<hr>

<%= render "layouts/sightings_form" %><br />

<% if @sighting.errors %>
    <ul>
        <% @sighting.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>